#ifndef LEDHARDWARE_H_INCLUDED
#define LEDHARDWARE_H_INCLUDED

#define LEDROT_PORT PORTA
#define LEDROT_PIN  PIN4_bm
#define LEDORANGE_PORT PORTA
#define LEDORANGE_PIN  PIN5_bm
#define LEDGRUEN_PORT PORTA
#define LEDGRUEN_PIN  PIN6_bm
#define LEDBLAU_PORT PORTA
#define LEDBLAU_PIN  PIN7_bm
// LED auf der Endat-Zusatz-Platine
#define LEDENDAT_PORT PORTB
#define LEDENDAT_PIN  PIN0_bm
// Schalter um das Messgerät einzuschalten
#define MGSWITCH_PORT PORTB
#define MGSWITCH_PIN  PIN3_bm

#define LEDROTSETUP LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON   LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF  LEDROT_PORT.OUTSET=LEDROT_PIN
#define LEDROT_TOGGLE  LEDROT_PORT.OUTTGL=LEDROT_PIN

#define LEDGRUENSETUP LEDGRUEN_PORT.DIRSET=LEDGRUEN_PIN
#define LEDGRUEN_ON   LEDGRUEN_PORT.OUTCLR=LEDGRUEN_PIN
#define LEDGRUEN_OFF  LEDGRUEN_PORT.OUTSET=LEDGRUEN_PIN
#define LEDGRUEN_TOGGLE  LEDGRUEN_PORT.OUTTGL=LEDGRUEN_PIN

#define LEDORANGESETUP LEDORANGE_PORT.DIRSET=LEDORANGE_PIN
#define LEDORANGE_ON   LEDORANGE_PORT.OUTCLR=LEDORANGE_PIN
#define LEDORANGE_OFF  LEDORANGE_PORT.OUTSET=LEDORANGE_PIN
#define LEDORANGE_TOGGLE  LEDORANGE_PORT.OUTTGL=LEDORANGE_PIN

#define LEDBLAUSETUP LEDBLAU_PORT.DIRSET=LEDBLAU_PIN
#define LEDBLAU_ON   LEDBLAU_PORT.OUTCLR=LEDBLAU_PIN
#define LEDBLAU_OFF  LEDBLAU_PORT.OUTSET=LEDBLAU_PIN
#define LEDBLAU_TOGGLE  LEDBLAU_PORT.OUTTGL=LEDBLAU_PIN

#define LEDBLAUSETUP LEDBLAU_PORT.DIRSET=LEDBLAU_PIN
#define LEDBLAU_ON   LEDBLAU_PORT.OUTCLR=LEDBLAU_PIN
#define LEDBLAU_OFF  LEDBLAU_PORT.OUTSET=LEDBLAU_PIN
#define LEDBLAU_TOGGLE  LEDBLAU_PORT.OUTTGL=LEDBLAU_PIN

#define LEDENDATSETUP LEDENDAT_PORT.DIRSET=LEDENDAT_PIN
#define LEDENDAT_ON   LEDENDAT_PORT.OUTCLR=LEDENDAT_PIN
#define LEDENDAT_OFF  LEDENDAT_PORT.OUTSET=LEDENDAT_PIN
#define LEDENDAT_TOGGLE  LEDENDAT_PORT.OUTTGL=LEDENDAT_PIN


#define MGSWITCHSETUP MGSWITCH_PORT.DIRSET=MGSWITCH_PIN
#define MGSWITCH_ON   MGSWITCH_PORT.OUTCLR=MGSWITCH_PIN
#define MGSWITCH_OFF  MGSWITCH_PORT.OUTSET=MGSWITCH_PIN
#define MGSWITCH_TOGGLE  MGSWITCH_PORT.OUTTGL=MGSWITCH_PIN



#endif // LEDHARDWARE_H_INCLUDED
